name: subscription-fetcher
description: Fetch subscription files from remote

inputs:
  config:
    description: Configuration file url
    required: true
  whitelist:
    description: Whitelist fetcher names(separated by comma)
    required: false
  blacklist:
    description: Blacklist fetcher names(separated by comma)
    required: false
  token:
    description: GitHub API token(default to GITHUB_TOKEN)
    required: false

runs:
  using: docker
  image: Dockerfile
